### ISSUE TITLE
Add CONTRIBUTING.md file

### ISSUE THREAD

**Issue by ankitjain28may** [ncs-jss/ncs-jss.github.io#2]

**Comment by rishabh-bansal** [comment]
Added PR #4 
Please label it under Hacktoberfest :)

**Comment by ankitjain28may** [comment]
@rishabh-bansal Thanks for the PR, will add the label.

**Comment by rishabh-bansal** [comment]
@ankitjain28may  I will make PR during October, is it okay for you? :)
Will surely do according to your requirement :)

**Comment by rsm23** [comment]
Please checkout #6

**Comment by rishabh-bansal** [comment]
@rsm23 I'm already working on this, you can't submit without @ankitjain28may  permission

**Comment by ankitjain28may** [comment]
@rsm23 hey, Thanks for your efforts but this issue is already assigned to @rishabh-bansal and if he wont be able to resolve this issue then you are most welcome. Keep Coding.

**Comment by ankitjain28may** [comment]
@rishabh-bansal are you going to fix this ?
